### ISSUE TITLE
paths option not working.

### ISSUE THREAD

**Issue by ccollie** [PabloSzx/bob-esbuild#200]
I've tried many ways of passing the `--paths` flag but the `tsconfig` paths are not replaced in the transpiled output. I've put together a basic repo to demonstrate here:

https://github.com/ccollie/bob-ts-test/tree/project-references

In any of the projects in `packages` run `yarn run compile:paths` and observe that the original path imports remain.

**Comment by PabloSzx** [comment]
just to keep in mind, a repo with 2000 dependencies is not minimal, I will put an eye on it, but keep in mind when doing that more strict projects won't accept a minimal repo like that

**Comment by PabloSzx** [comment]
![image](https://user-images.githubusercontent.com/8672915/143921098-f28c0ece-4846-4cbc-894f-4d837e0c620a.png)

not even "tsc" does the path mapping as the repo expects

**Comment by PabloSzx** [comment]
I found an issue with `bob-ts` and the paths resolution, it should be fixed in [v2.0.0](https://github.com/PabloSzx/bob-esbuild/releases/tag/bob-ts%402.0.0), it might not be related with what you are reporting here, but as I already mentioned, if a package has a direct reference, for example, in a monorepo, that will always have priority over tsconfig paths, with is shown when not even tsc itself will do the compilation in the example you gave.

If you find another issue you can reopen this issue giving more info
